version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flavorai
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./flavorai-backend
    ports:
      - "3001:3001"
      - "5555:5555"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/flavorai
      JWT_SECRET: supersecret
    depends_on:
      - db

  # frontend:
  #   build:
  #     context: ./flavorai-frontend
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./flavorai-frontend:/app
  #     - /app/node_modules
  #     - /app/.next
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #     - WATCHPACK_POLLING=true
  #     - NEXT_PUBLIC_API_URL=http://localhost:3001
  #   depends_on:
  #     - backend

  frontend:
    build:
      context: ./flavorai-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3001
    depends_on:
      - backend
volumes:
  db-data:
